#!/usr/bin/env python3
"""Generate a C file registry + cache.appcache from a staged dist directory.

Scans <dist_dir> recursively and produces:
  - <header_out>  : file_registry.h  (FileEntry struct + extern table)
  - <source_out>  : file_registry.c  (byte arrays + lookup function)
  - <dist_dir>/cache.appcache       (AppCache manifest for the PS5 browser)

Based on ps5-webkit-autoloader's gen_file_registry.py by PLK,
simplified for Console Homebrew Hub.

Usage: gen_file_registry.py <dist_dir> <header_out> <source_out>
"""

import os
import posixpath
import re
import sys
import zlib

CONTENT_TYPES = {
    ".html": "text/html; charset=utf-8",
    ".htm": "text/html; charset=utf-8",
    ".css": "text/css",
    ".js": "application/javascript",
    ".json": "application/json",
    ".svg": "image/svg+xml",
    ".png": "image/png",
    ".jpg": "image/jpeg",
    ".jpeg": "image/jpeg",
    ".gif": "image/gif",
    ".ico": "image/x-icon",
    ".appcache": "text/cache-manifest",
    ".txt": "text/plain",
    ".elf": "application/octet-stream",
    ".bin": "application/octet-stream",
}

EXCLUDE_PATTERNS = [
    "/.git/",
    "/.github/",
    "/chh-src/",
    "/tools/",
    "/cache.appcache",
]


def detect_content_type(path):
    ext = os.path.splitext(path)[1].lower()
    return CONTENT_TYPES.get(ext, "application/octet-stream")


def include_in_registry(path):
    for pat in EXCLUDE_PATTERNS:
        if pat in path or path.endswith(pat.rstrip("/")):
            return False
    return True


def compress_entry(data):
    if len(data) < 64:
        return data, False
    co = zlib.compressobj(level=9, wbits=-15)
    comp = co.compress(data) + co.flush()
    if len(comp) >= len(data):
        return data, False
    return comp, True


def emit_c_array(out, name, data):
    out.write(f"static const unsigned char {name}[] = {{\n")
    for i in range(0, len(data), 12):
        chunk = ", ".join(f"0x{b:02x}" for b in data[i : i + 12])
        out.write(f"    {chunk},\n")
    out.write("};\n")


def strip_manifest_attr(data, path):
    """Strip manifest= from exploit core HTML (same as _patch_exploit_cores)."""
    if not path.endswith(".html"):
        return data
    if b"/core/" not in path.encode() and b"\\core\\" not in path.encode():
        return data
    text = data.decode("utf-8", errors="replace")
    patched = re.sub(
        r'(<html)\s+manifest\s*=\s*["\'][^"\']*["\']',
        r'\1',
        text,
        count=1,
    )
    return patched.encode("utf-8")


def build_manifest(files):
    lines = [
        "CACHE MANIFEST",
        "# CHH offline cache — auto-generated by tools/gen_file_registry.py",
        "",
        "CACHE:",
    ]
    for path, _ in files:
        if path == "/cache.appcache":
            continue
        lines.append(path)
    lines += [
        "",
        "NETWORK:",
        "/install",
        "/version",
        "*",
        "",
    ]
    return "\n".join(lines)


def main():
    if len(sys.argv) != 4:
        print("Usage: gen_file_registry.py <dist_dir> <header_out> <source_out>")
        sys.exit(1)

    dist_dir, header_out, source_out = sys.argv[1:4]

    if not os.path.isdir(dist_dir):
        print(f"Error: {dist_dir} not found or not a directory.")
        sys.exit(1)

    files = []
    for root, dirs, names in os.walk(dist_dir):
        dirs.sort()
        for name in sorted(names):
            full = os.path.join(root, name)
            rel = os.path.relpath(full, dist_dir).replace(os.sep, "/")
            path = f"/{rel}"
            if not include_in_registry(path):
                continue
            files.append((path, full))
    files.sort(key=lambda f: f[0])

    manifest_path = os.path.join(dist_dir, "cache.appcache")
    with open(manifest_path, "w") as f:
        f.write(build_manifest(files))
    files.append(("/cache.appcache", manifest_path))
    files.sort(key=lambda f: f[0])

    # Header
    with open(header_out, "w") as out:
        out.write("/* Auto-generated by tools/gen_file_registry.py — do not edit. */\n\n")
        out.write("#ifndef FILE_REGISTRY_H\n")
        out.write("#define FILE_REGISTRY_H\n\n")
        out.write("typedef struct {\n")
        out.write("    const char *path;\n")
        out.write("    const unsigned char *data;\n")
        out.write("    unsigned int size;\n")
        out.write("    unsigned int orig_size;\n")
        out.write("    unsigned char compressed;\n")
        out.write("    const char *content_type;\n")
        out.write("} FileEntry;\n\n")
        out.write("extern const FileEntry file_registry[];\n")
        out.write("extern const unsigned int file_registry_count;\n\n")
        out.write("const FileEntry *file_registry_find(const char *path);\n\n")
        out.write("#endif /* FILE_REGISTRY_H */\n")

    # Source
    with open(source_out, "w") as out:
        out.write("/* Auto-generated by tools/gen_file_registry.py — do not edit. */\n\n")
        out.write('#include <string.h>\n')
        out.write('#include "file_registry.h"\n\n')

        entries = []
        total_raw = 0
        total_stored = 0
        for i, (path, full) in enumerate(files):
            with open(full, "rb") as f:
                data = f.read()
            data = strip_manifest_attr(data, path)
            stored, compressed = compress_entry(data)
            emit_c_array(out, f"file_{i}", stored)
            out.write("\n")
            entries.append((path, compressed, len(data), len(stored)))
            total_raw += len(data)
            total_stored += len(stored)

        out.write("const FileEntry file_registry[] = {\n")
        for i, (path, full) in enumerate(files):
            content_type = detect_content_type(path)
            _, compressed, orig_size, stored_size = entries[i]
            out.write(
                f'    {{ "{path}", file_{i}, {stored_size}, {orig_size}, '
                f'{1 if compressed else 0}, "{content_type}" }},\n'
            )
        out.write("};\n\n")
        out.write("const unsigned int file_registry_count =\n")
        out.write("    sizeof(file_registry) / sizeof(file_registry[0]);\n\n")
        out.write("const FileEntry *file_registry_find(const char *path) {\n")
        out.write("    if (!path) return NULL;\n")
        out.write("    for (unsigned int i = 0; i < file_registry_count; i++) {\n")
        out.write('        if (strcmp(file_registry[i].path, path) == 0)\n')
        out.write("            return &file_registry[i];\n")
        out.write("    }\n")
        out.write("    return NULL;\n")
        out.write("}\n")

    print(f"Generated {header_out} and {source_out}")
    print(f"  {len(files)} files, {total_raw:,} bytes raw, {total_stored:,} bytes stored "
          f"({100 * total_stored / max(total_raw, 1):.0f}%)")


if __name__ == "__main__":
    main()
